repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: CHANGELOG.md
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key


- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shfmt
      args: ['-l', '-i', '2', '-ci', '-sr', '-w']
    - id: shellcheck

# Dockerfile linter
- repo: https://github.com/hadolint/hadolint
  rev: v2.13.0-beta
  hooks:
    - id: hadolint
      args: [
        '--ignore', 'DL3007', # Using latest
        '--ignore', 'DL3013', # Pin versions in pip
        '--ignore', 'DL3027', # Do not use apt
        '--ignore', 'DL3059', # Docker `RUN`s shouldn't be consolidated here
        '--ignore', 'DL4006', # Not related to alpine
        '--ignore', 'SC1091', # Useless check
        '--ignore', 'SC2015', # Useless check
        '--ignore', 'SC3037', # Not related to alpine
      ]

# JSON5 Linter
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
  - id: prettier
    # https://prettier.io/docs/en/options.html#parser
    files: '.json5$'


##########
# PYTHON #
##########

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
    - id: ruff
      args: [--fix]
      types_or: [python, pyi]
    - id: ruff-format
      types_or: [python, pyi]
      args: [--config, format.quote-style = 'single', --config, line-length = 100]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort
      args: [--force-single-line, --profile=black]

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
    - id: add-trailing-comma

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.4
  hooks:
    - id: autopep8
      args:
      - -i
      - --max-line-length=100

# Usage: http://pylint.pycqa.org/en/latest/user_guide/message-control.html
- repo: https://github.com/PyCQA/pylint
  rev: v3.1.0
  hooks:
    - id: pylint
      args:
      - --disable=import-error # E0401. Locally you could not have all imports.
      - --disable=fixme # W0511. 'TODO' notations.
      - --disable=logging-fstring-interpolation # Conflict with "use a single formatting" WPS323
      - --disable=ungrouped-imports # ignore `if TYPE_CHECKING` case. Other do reorder-python-imports
      exclude: test_.+\.py$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
    - id: mypy
      args: [
        --ignore-missing-imports,
        --disallow-untyped-calls,
        --warn-redundant-casts,
      ]

- repo: https://github.com/pycqa/flake8.git
  rev: 7.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-2020
    - flake8-docstrings
    - flake8-pytest-style
    - wemake-python-styleguide
    args:
    - --max-returns=2 # Default settings
    - --max-arguments=4 # Default settings
    # https://www.flake8rules.com/
    # https://wemake-python-stylegui.de/en/latest/pages/usage/violations/index.html
    - --extend-ignore=
              WPS210 <!-- Found too many local variables. Handled by pylint -->
              WPS226 <!-- Found string literal over-use - append > 3 -->
              WPS300 <!-- Found local folder import. Nothing bad about this -->
              WPS305 <!-- Found `f` string -->
              WPS323 <!-- Found `%` string formatting. Conflict with pytlint "Use lazy % formatting in logging functions"
              E501   <!-- line too long (> 79 characters). Use 100 -->
              I      <!-- opt out of using isort in favor of reorder-python-imports -->
              S404 <!-- Consider possible security implications associated with the subprocess module. Yep, we execute external tools -->
              S603 <!-- subprocess call - check for execution of untrusted input -->
              <!-- Google Python style is not RST until after processed by Napoleon -->
              <!-- See https://github.com/peterjc/flake8-rst-docstrings/issues/17 -->
              RST201 RST203 RST301

              # WPS211  <!-- Found too many arguments. Handled by pylint -->
              # WPS420  <!-- Forbid some python keywords. Disabled as fix proposals unclear -->
              # RST,    <!-- Conflict with DAR -->
    exclude: test_.+\.py$
